# This is a basic workflow to help you get started with Actions

name: Put bug label

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
   types: [opened, edited]

  # Allows you to run this workflow manually from the Actions tab
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-bug-in-the-issue-title:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: check issue title
        env:
          ISSUE_TITLE: ${{ toJson(github.event.issue.title) }}
        if: contains(github.event.issue.title, 'bug')
        run : | 
          echo "$ISSUE_TITLE - it's a bug!, Let's put 'bug' label"
          npm install @actions/core
          npm install @actions/github
          npm install @octokit/rest
      
      - name : put label
        uses : ./
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}


